name: qtodotxt2
version: git
summary: gui frontend for todo.txt files
description: gui frontend for todo.txt files

confinement: devmode

parts:
  qtodotxt2:
    plugin: python
    source: https://github.com/tiny6996/QTodoTxt2.git

apps:
  qtodotxt2:
    command: bin/qtodotxt
