name: qtodotxt2
version: git
summary: gui frontend for todo.txt files
description: gui frontend for todo.txt files

confinement: devmode

parts:
  qtodotxt2:
    plugin: python
    source: .

apps:
  qtodotxt2:
    command: bin/qtodotxt
